### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by InternetRamen** [wombat24455/MikebotDiscordBot#19]
Is there anything I can help code? I would love to contribute.

**Comment by Cwavs** [comment]
As far as I know we don't have anything in particular to work on, you'll need to wait for wombat to gett back to you on that. However if you have something you want adding, or just general improvements to the code, feel free to make a push request and we'll review it. I'll close this and talk to wombat about maybe settign up a public roadmap of some sort.

**Comment by Cwavs** [comment]
Turns out we already have a roadmap [here](https://github.com/wombat24455/MikebotDiscordBot/projects/1)
