### ISSUE TITLE
>$reportbug

### ISSUE THREAD

**Issue by wombat24455** [wombat24455/MikebotDiscordBot#7]
Use this command to report any bugs or things that seem broken
This command will be added some time in the future

**Comment by InternetRamen** [comment]
Could I contribute on this command?

**Comment by wombat24455** [comment]
i'll discuss it with the others, will get back to you soon

**Comment by wombat24455** [comment]
I have discussed with the others and they said you can contribute to the
command.

**Comment by InternetRamen** [comment]
@wombat24455 Thank you for the opportunity.

**Comment by wombat24455** [comment]
No problem.
